/*********************************************************
 **
 ** File  aol_line_width_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3a (build i2)
 **
 ** Date of generation: 2025-10-10T11:03:20
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.3\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir E:\yxiang\gpuzx_scade\NDto2C\ND\specification_Code E:\yxiang\gpuzx_scade\NDto2C\ND\line_width_table.swt
 *********************************************************/

#ifndef _AOL_LINE_WIDTH_TABLE_H
#define _AOL_LINE_WIDTH_TABLE_H

#include "sgl_types.h"

/* Line width table definition */
extern const sgl_line_width aol_line_width_table[8UL];

extern SGLint32 aol_line_width_table_size;

#endif /* _AOL_LINE_WIDTH_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2025-10-10T11:03:20
 *********************************************************/

