/*********************************************************
 **
 ** File  aol_font_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3a (build i2)
 **
 ** Date of generation: 2025-10-10T11:03:34
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.3\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir E:\yxiang\gpuzx_scade\NDto2C\ND\specification_Code E:\yxiang\gpuzx_scade\NDto2C\ND\font_table.sft
 *********************************************************/

#ifndef _AOL_FONT_TABLE_H
#define _AOL_FONT_TABLE_H

#include "glf.h"

/* Fonts definition */

typedef struct
{
  glf_type_font_table_header tr_header;
  glf_type_font tr_fonts_description[20UL];
  glf_type_map_property tr_maps[35UL];
  glf_type_character_bitmap5 tr_characters0[101UL];
  glf_type_character_bitmap5 tr_characters1[101UL];
  glf_type_character_bitmap6 tr_characters2[101UL];
  glf_type_character_bitmap6 tr_characters3[101UL];
  glf_type_character_bitmap7 tr_characters4[101UL];
  glf_type_character_bitmap2 tr_characters5[475UL];
  glf_type_character_bitmap2 tr_characters6[475UL];
  glf_type_character_bitmap2 tr_characters7[475UL];
  glf_type_character_bitmap2 tr_characters8[475UL];
  glf_type_character_bitmap2 tr_characters9[366UL];
  glf_type_character_bitmap2 tr_characters10[366UL];
  glf_type_character_bitmap2 tr_characters11[366UL];
  glf_type_character_bitmap2 tr_characters12[366UL];
  glf_type_character_bitmap2 tr_characters13[3316UL];
  glf_type_character_bitmap2 tr_characters14[3316UL];
  glf_type_character_bitmap2 tr_characters15[3755UL];
  glf_type_character_bitmap2 tr_characters16[3870UL];
  glf_type_character_bitmap2 tr_characters17[3870UL];
  glf_type_character_bitmap2 tr_characters18[3316UL];
} aol_font_table_type;

extern SGLuint8 aol_font_table_texture0[530939UL];
extern SGLuint8 aol_font_table_texture1[500016UL];
extern SGLuint8 aol_font_table_texture2[505907UL];
extern SGLuint8 aol_font_table_texture3[463816UL];
extern SGLuint8 aol_font_table_texture4[476306UL];
extern SGLuint8 aol_font_table_texture5[470030UL];
extern SGLuint8 aol_font_table_texture6[453918UL];
extern SGLuint8 aol_font_table_texture7[450013UL];
extern SGLuint8 aol_font_table_texture8[447224UL];
extern SGLuint8 aol_font_table_texture9[432087UL];
extern SGLuint8 aol_font_table_texture10[506356UL];
extern SGLuint8 aol_font_table_texture11[494559UL];
extern SGLuint8 aol_font_table_texture12[491041UL];
extern SGLuint8 aol_font_table_texture13[469475UL];
extern SGLuint8 aol_font_table_texture14[466231UL];
extern SGLuint8 aol_font_table_texture15[455782UL];
extern SGLuint8 aol_font_table_texture16[452032UL];
extern SGLuint8 aol_font_table_texture17[437919UL];
extern SGLuint8 aol_font_table_texture18[448003UL];
extern SGLuint8 aol_font_table_texture19[466652UL];
extern SGLuint8 aol_font_table_texture20[457862UL];
extern SGLuint8 aol_font_table_texture21[452198UL];
extern SGLuint8 aol_font_table_texture22[443218UL];
extern SGLuint8 aol_font_table_texture23[449993UL];
extern SGLuint8 aol_font_table_texture24[477243UL];
extern SGLuint8 aol_font_table_texture25[466360UL];
extern SGLuint8 aol_font_table_texture26[447889UL];
extern SGLuint8 aol_font_table_texture27[437613UL];
extern SGLuint8 aol_font_table_texture28[447936UL];
extern SGLuint8 aol_font_table_texture29[498909UL];
extern SGLuint8 aol_font_table_texture30[511781UL];
extern SGLuint8 aol_font_table_texture31[477382UL];
extern SGLuint8 aol_font_table_texture32[460564UL];
extern SGLuint8 aol_font_table_texture33[457291UL];
extern SGLuint8 aol_font_table_texture34[123301UL];

extern const aol_font_table_type aol_font_table;

#define AOL_FONT_TABLE_SIZE (sizeof(aol_font_table_type))

#endif /* _AOL_FONT_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2025-10-10T11:03:34
 *********************************************************/

