/*********************************************************
 **
 ** File  aol_imported_functions.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3a (build i2)
 **
 ** Date of generation: 2025-10-10T11:03:39
 ** Command line: ScadeDisplayKCG.exe -outdir E:\yxiang\gpuzx_scade\NDto2C\ND\specification_Code E:\yxiang\gpuzx_scade\NDto2C\ND\specification.sgfx
 *********************************************************/

#ifndef _AOL_IMPORTED_FUNCTIONS_H
#define _AOL_IMPORTED_FUNCTIONS_H

#include "sgl_types.h"

/* Imported functions */

#endif /* _AOL_IMPORTED_FUNCTIONS_H */

/*********************************************************
 ** End of file
 ** End of generation: 2025-10-10T11:03:39
 *********************************************************/

