/*********************************************************
 **
 ** File  aol_color_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3a (build i2)
 **
 ** Date of generation: 2025-10-10T11:03:19
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.3\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir E:\yxiang\gpuzx_scade\NDto2C\ND\specification_Code E:\yxiang\gpuzx_scade\NDto2C\ND\color_table.sct
 *********************************************************/

#ifndef _AOL_COLOR_TABLE_H
#define _AOL_COLOR_TABLE_H

#include "sgl_types.h"

/* Color table definition */
extern const sgl_color aol_color_table[128UL];

extern SGLint32 aol_color_table_size;

extern SGLint32 aol_color_table_background_index;

#endif /* _AOL_COLOR_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2025-10-10T11:03:19
 *********************************************************/

