/*********************************************************
 **
 ** File  aol_symbology_layer.h
 **
 ** Specification File:  E:\yxiang\gpuzx_scade\NDto2C\ND\specification.sgfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3a (build i2)
 **
 ** Date of generation: 2025-10-10T11:03:39
 ** Command line: ScadeDisplayKCG.exe -outdir E:\yxiang\gpuzx_scade\NDto2C\ND\specification_Code E:\yxiang\gpuzx_scade\NDto2C\ND\specification.sgfx
 *********************************************************/

#ifndef _AOL_SYMBOLOGY_LAYER_H
#define _AOL_SYMBOLOGY_LAYER_H

#include "sgl_types.h"
#include "kcg_assign.h"


/* Accessors */
#ifndef aol_symbology_layer_G_tHdg
#define aol_symbology_layer_G_tHdg(_C_) (_C_)->tHdg
#define aol_symbology_layer_S_tHdg(_C_,_V_) (_C_)->tHdg = (_V_)
#endif /* aol_symbology_layer_G_tHdg */
#ifndef aol_symbology_layer_G_LON_EW
#define aol_symbology_layer_G_LON_EW(_C_) (_C_)->LON_EW
#define aol_symbology_layer_S_LON_EW(_C_,_V_) kcg_assign((_C_)->LON_EW, (_V_), sizeof(SGLuint8 [255UL]))
#endif /* aol_symbology_layer_G_LON_EW */
#ifndef aol_symbology_layer_G_LON_D
#define aol_symbology_layer_G_LON_D(_C_) (_C_)->LON_D
#define aol_symbology_layer_S_LON_D(_C_,_V_) kcg_assign((_C_)->LON_D, (_V_), sizeof(SGLuint8 [255UL]))
#endif /* aol_symbology_layer_G_LON_D */
#ifndef aol_symbology_layer_G_LON_M
#define aol_symbology_layer_G_LON_M(_C_) (_C_)->LON_M
#define aol_symbology_layer_S_LON_M(_C_,_V_) kcg_assign((_C_)->LON_M, (_V_), sizeof(SGLuint8 [255UL]))
#endif /* aol_symbology_layer_G_LON_M */
#ifndef aol_symbology_layer_G_LON_S
#define aol_symbology_layer_G_LON_S(_C_) (_C_)->LON_S
#define aol_symbology_layer_S_LON_S(_C_,_V_) kcg_assign((_C_)->LON_S, (_V_), sizeof(SGLuint8 [255UL]))
#endif /* aol_symbology_layer_G_LON_S */
#ifndef aol_symbology_layer_G_LAT_NS
#define aol_symbology_layer_G_LAT_NS(_C_) (_C_)->LAT_NS
#define aol_symbology_layer_S_LAT_NS(_C_,_V_) kcg_assign((_C_)->LAT_NS, (_V_), sizeof(SGLuint8 [255UL]))
#endif /* aol_symbology_layer_G_LAT_NS */
#ifndef aol_symbology_layer_G_LAT_D
#define aol_symbology_layer_G_LAT_D(_C_) (_C_)->LAT_D
#define aol_symbology_layer_S_LAT_D(_C_,_V_) kcg_assign((_C_)->LAT_D, (_V_), sizeof(SGLuint8 [255UL]))
#endif /* aol_symbology_layer_G_LAT_D */
#ifndef aol_symbology_layer_G_LAT_M
#define aol_symbology_layer_G_LAT_M(_C_) (_C_)->LAT_M
#define aol_symbology_layer_S_LAT_M(_C_,_V_) kcg_assign((_C_)->LAT_M, (_V_), sizeof(SGLuint8 [255UL]))
#endif /* aol_symbology_layer_G_LAT_M */
#ifndef aol_symbology_layer_G_LAT_S
#define aol_symbology_layer_G_LAT_S(_C_) (_C_)->LAT_S
#define aol_symbology_layer_S_LAT_S(_C_,_V_) kcg_assign((_C_)->LAT_S, (_V_), sizeof(SGLuint8 [255UL]))
#endif /* aol_symbology_layer_G_LAT_S */
#ifndef aol_symbology_layer_G_ND_VIS
#define aol_symbology_layer_G_ND_VIS(_C_) (_C_)->ND_VIS
#define aol_symbology_layer_S_ND_VIS(_C_,_V_) (_C_)->ND_VIS = (_V_)
#endif /* aol_symbology_layer_G_ND_VIS */

/* Context type */
typedef struct aol_typ_symbology_layer_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat tHdg;
  SGLuint8 LON_EW[255UL];
  SGLuint8 LON_D[255UL];
  SGLuint8 LON_M[255UL];
  SGLuint8 LON_S[255UL];
  SGLuint8 LAT_NS[255UL];
  SGLuint8 LAT_D[255UL];
  SGLuint8 LAT_M[255UL];
  SGLuint8 LAT_S[255UL];
  SGLbool ND_VIS;
} aol_typ_symbology_layer;

/* Associated functions */
extern void aol_symbology_layer_init(aol_typ_symbology_layer *pContext);
extern void aol_symbology_layer_predraw(aol_typ_symbology_layer *pContext);
extern void aol_symbology_layer_draw(aol_typ_symbology_layer *pContext, SGLint32 pPriority);

#endif /* _AOL_SYMBOLOGY_LAYER_H */

/*********************************************************
 ** End of file
 ** End of generation: 2025-10-10T11:03:39
 *********************************************************/

