/*********************************************************
 **
 ** File  aol_texture_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3a (build i2)
 **
 ** Date of generation: 2025-10-10T11:03:23
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.3\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir E:\yxiang\gpuzx_scade\NDto2C\ND\specification_Code E:\yxiang\gpuzx_scade\NDto2C\ND\texture_table.stt
 *********************************************************/

#ifndef _AOL_TEXTURE_TABLE_H
#define _AOL_TEXTURE_TABLE_H

#include "sgl_types.h"

/* Textures definition */
#define AOL_TEXTURE_TABLE_SIZE 0

extern void aol_texture_table(void);

#endif /* _AOL_TEXTURE_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2025-10-10T11:03:23
 *********************************************************/

