/*********************************************************
 **
 ** File  aol_line_width_table.c
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3a (build i2)
 **
 ** Date of generation: 2025-10-10T11:03:20
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.3\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir E:\yxiang\gpuzx_scade\NDto2C\ND\specification_Code E:\yxiang\gpuzx_scade\NDto2C\ND\line_width_table.swt
 *********************************************************/

#include "aol_line_width_table.h"

/* Line width table definition */
const sgl_line_width aol_line_width_table[8UL] = 
{
{ 1.2F, 1.5F, 3.F }, /* 0 : LW0 */
{ 2.5F, 1.5F, 3.5F }, /* 1 : LW1 */
{ 3.5F, 2.5F, 4.2F }, /* 2 : LW2 */
{ 4.5F, 3.5F, 5.5F }, /* 3 : LW3 */
{ 5.5F, 4.5F, 6.5F }, /* 4 : LW4 */
{ 6.5F, 5.5F, 7.5F }, /* 5 : LW5 */
{ 7.5F, 6.5F, 8.5F }, /* 6 : LW6 */
{ 8.5F, 7.5F, 9.5F }  /* 7 : LW7 */
};

SGLint32 aol_line_width_table_size = 8UL;

/*********************************************************
 ** End of file
 ** End of generation: 2025-10-10T11:03:20
 *********************************************************/

