/*********************************************************
 **
 ** File  aol_line_stipple_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3a (build i2)
 **
 ** Date of generation: 2025-10-10T11:03:22
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.3\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir E:\yxiang\gpuzx_scade\NDto2C\ND\specification_Code E:\yxiang\gpuzx_scade\NDto2C\ND\line_stipple_table.sst
 *********************************************************/

#ifndef _AOL_LINE_STIPPLE_TABLE_H
#define _AOL_LINE_STIPPLE_TABLE_H

#include "sgl_types.h"

/* Line stipple table definition */
extern const sgl_linestipple aol_line_stipple_table[5UL];

extern SGLint32 aol_line_stipple_table_size;

#endif /* _AOL_LINE_STIPPLE_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2025-10-10T11:03:22
 *********************************************************/

