/*********************************************************
 **
 ** File  aol_symbology_layer.c
 **
 ** Specification File:  E:\yxiang\gpuzx_scade\NDto2C\ND\specification.sgfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3a (build i2)
 **
 ** Date of generation: 2025-10-10T11:03:39
 ** Command line: ScadeDisplayKCG.exe -outdir E:\yxiang\gpuzx_scade\NDto2C\ND\specification_Code E:\yxiang\gpuzx_scade\NDto2C\ND\specification.sgfx
 *********************************************************/

#include "aol_symbology_layer.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_symbology_layer_init(aol_typ_symbology_layer *pContext)
{
  aol_symbology_layer_S_tHdg(pContext, 0.0F);
  {
    static SGLuint8 _lArray0[255UL] = {0U};
    aol_symbology_layer_S_LON_EW(pContext, _lArray0);
  }
  {
    static SGLuint8 _lArray0[255UL] = {0U};
    aol_symbology_layer_S_LON_D(pContext, _lArray0);
  }
  {
    static SGLuint8 _lArray0[255UL] = {0U};
    aol_symbology_layer_S_LON_M(pContext, _lArray0);
  }
  {
    static SGLuint8 _lArray0[255UL] = {0U};
    aol_symbology_layer_S_LON_S(pContext, _lArray0);
  }
  {
    static SGLuint8 _lArray0[255UL] = {0U};
    aol_symbology_layer_S_LAT_NS(pContext, _lArray0);
  }
  {
    static SGLuint8 _lArray0[255UL] = {0U};
    aol_symbology_layer_S_LAT_D(pContext, _lArray0);
  }
  {
    static SGLuint8 _lArray0[255UL] = {0U};
    aol_symbology_layer_S_LAT_M(pContext, _lArray0);
  }
  {
    static SGLuint8 _lArray0[255UL] = {0U};
    aol_symbology_layer_S_LAT_S(pContext, _lArray0);
  }
  aol_symbology_layer_S_ND_VIS(pContext, SGL_FALSE);

}

void aol_symbology_layer_predraw(aol_typ_symbology_layer *pContext)
{

}

void aol_symbology_layer_draw(aol_typ_symbology_layer *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, 0L)) {

    /* Object: symbology_layer, Type: layer, OID: f46d03b6-8502-4d91-8842-2d612e6d129c */
    {
      sglPushMatrixAndTranslate(384.0F, 512.0F);

      /* Object: group, Type: container, OID: bf173ae4-3840-4d2a-9543-090a044819be */
      {
        if (aol_symbology_layer_G_ND_VIS(pContext)) {

          /* Object: LON, Type: container, OID: a2e15a66-5104-49c4-8dc0-8113b7d27fdb */
          {

            /* Object: E, Type: text, OID: bc1e8656-8ebb-4b43-ad81-efad0740c043 */
            {
              sglSetActiveMasks(SGL_NO_MASK);
              sglIndexColori(41L);
              sglIndexHaloColori(-1L);
              sglIndexFontLineWidthi(2L);
              sglIndexFonti(3L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_BOTTOM);
              sgluWriteText(-176.0F, -460.0F, aol_symbology_layer_G_LON_EW(pContext), 255L);
            }

            /* Object: LON_D, Type: text, OID: 659a6fba-105d-4e69-8f18-521b3307d227 */
            {
              sgluWriteText(-154.0F, -460.0F, aol_symbology_layer_G_LON_D(pContext), 255L);
            }

            /* Object: text, Type: text, OID: 8ff07f9c-7095-4b79-bb40-dbf47281b6ab */
            {
              static SGLuint8 _lArray0_text[255UL] = {176U};
              sgluWriteText(-111.5F, -457.25F, _lArray0_text, 255L);
            }

            /* Object: text_1, Type: text, OID: 86d1c222-8514-4a0b-b3a1-0ae9e19fd0ea */
            {
              static SGLuint8 _lArray0_text_1[255UL] = {39U};
              sgluWriteText(-62.25F, -457.5F, _lArray0_text_1, 255L);
            }

            /* Object: text_2, Type: text, OID: 930c1b12-918e-4e7f-9f83-9efedb633ce8 */
            {
              static SGLuint8 _lArray0_text_2[255UL] = {0U};
              sglIndexFonti(13L);
              sgluWriteText(-37.0F, -459.25F, _lArray0_text_2, 255L);
            }

            /* Object: line, Type: line, OID: 41b658f3-4033-427c-8b2a-42f3fd702f70 */
            {
              /* outlined object part */
              sglDisable(SGL_TEXTURE_2D);
              sglIndexLineWidthi(0L);
              sglIndexLineStipplei(0L);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINES);
              sglVertex2f(-16.0F, -438.0F);
              sglVertex2f(-15.875F, -443.75F);
            }

            /* Object: line_1, Type: line, OID: 76137a6f-b298-4f3d-a9f4-8f818d59da12 */
            {
              /* outlined object part */
              sglVertex2f(-11.375F, -437.875F);
              sglVertex2f(-11.375F, -444.125F);
              sglEnd();
            }

            /* Object: LON_M, Type: text, OID: f8336f81-b343-4513-b656-66323da8f068 */
            {
              sglIndexFonti(3L);
              sgluWriteText(-93.25F, -460.0F, aol_symbology_layer_G_LON_M(pContext), 255L);
            }

            /* Object: LON_S, Type: text, OID: 0d0071b0-13b3-4fab-8cbd-7df5f77e8e6d */
            {
              sgluWriteText(-49.25F, -460.0F, aol_symbology_layer_G_LON_S(pContext), 255L);
            }
          }

          /* Object: HDG_BUG, Type: container, OID: 9bfa8c54-5f6d-48e4-889d-fd0e03f888ab */
          {
            sglPushMatrixAndTranslate(-1.0F, 118.5F);

            /* Object: line_2, Type: line, OID: 5b94068e-fee9-4363-9bb7-42fa57fc7890 */
            {
              /* outlined object part */
              sglIndexColori(2L);
              sglIndexLineWidthi(1L);
              sglBegin(SGL_LINE_STRIP);
              sglVertex2f(-27.0F, 308.0F);
              sglVertex2f(28.0F, 308.0F);
              sglVertex2f(28.0F, 281.0F);
              sglVertex2f(13.5F, 281.0F);
              sglVertex2f(-1e-006F, 274.0F);
              sglVertex2f(-13.5F, 281.0F);
              sglVertex2f(-27.0F, 281.0F);
              sglVertex2f(-27.0F, 308.0F);
              sglEnd();
            }

            /* Object: tHdg, Type: bifont, OID: 608a3a49-d9de-4193-9122-343f4d39e191 */
            {
              sglIndexFonti(5L);
              sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_BOTTOM);
              sglSetSecondFontAttributes(2L, 0L, 2L);
              {
                sgl_numeric_format _lFormat;
                _lFormat.l_integralPart = 3L;
                _lFormat.l_fractionalPart = 0L;
                _lFormat.l_secondFontPos = 0L;
                _lFormat.b_separator = 46U;
                _lFormat.b_leadingZeros = SGL_FALSE;
                _lFormat.l_displaySign = SGL_SIGN_NEVER;
                sgluWriteFloat(0.0F, 288.25F, aol_symbology_layer_G_tHdg(pContext), &_lFormat);
              }
            }
            sglPopMatrixAndTranslate();
          }

          /* Object: text_3, Type: text, OID: 35258537-c543-44d2-a197-f34757470667 */
          {
            static SGLuint8 _lArray0_text_3[255UL] = {84U};
            sglIndexColori(41L);
            sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_BOTTOM);
            sgluWriteText(-49.0F, 408.5F, _lArray0_text_3, 255L);
          }

          /* Object: line_3, Type: line, OID: 69cd6908-8569-43bc-9172-489af3676c60 */
          {
            /* outlined object part */
            sglIndexColori(2L);
            sglBegin(SGL_LINES);
            sglVertex2f(20.0F, 0.0F);
            sglVertex2f(-20.0F, 0.0F);
          }

          /* Object: line_4, Type: line, OID: 3cd2dd49-9f0c-4dda-9812-ca17ef37836c */
          {
            /* outlined object part */
            sglVertex2f(10.0F, -16.0F);
            sglVertex2f(-10.0F, -16.0F);
          }

          /* Object: line_5, Type: line, OID: dc41b81d-1c85-45cc-b66c-35bd3e561e17 */
          {
            /* outlined object part */
            sglVertex2f(0.0F, -20.0F);
            sglVertex2f(0.0F, 15.0F);
            sglEnd();
          }

          /* Object: LAT, Type: container, OID: 2ca217d0-bd2c-4f85-83e0-ed9a1ba76237 */
          {
            sglPushMatrixAndTranslate(180.0F, 0.0F);

            /* Object: N, Type: text, OID: 4fc481cd-e9c0-4199-a422-74c3fe409dbf */
            {
              sglIndexColori(41L);
              sglIndexFonti(3L);
              sgluWriteText(-176.0F, -460.0F, aol_symbology_layer_G_LAT_NS(pContext), 255L);
            }

            /* Object: LAT_D, Type: text, OID: b8ac9516-7c38-4170-be0e-f69c4edc1eb9 */
            {
              sgluWriteText(-144.0F, -460.0F, aol_symbology_layer_G_LAT_D(pContext), 255L);
            }

            /* Object: text_4, Type: text, OID: 8deaf2b7-b28e-4f1d-8d59-61d499ff1687 */
            {
              static SGLuint8 _lArray0_text_4[255UL] = {176U};
              sgluWriteText(-111.5F, -457.25F, _lArray0_text_4, 255L);
            }

            /* Object: text_5, Type: text, OID: 5bf92485-8255-467a-a84c-b45ef9a72144 */
            {
              static SGLuint8 _lArray0_text_5[255UL] = {39U};
              sgluWriteText(-62.25F, -457.5F, _lArray0_text_5, 255L);
            }

            /* Object: text_6, Type: text, OID: 6fa14198-fefd-434e-8e45-85df178d1f86 */
            {
              static SGLuint8 _lArray0_text_6[255UL] = {0U};
              sglIndexFonti(13L);
              sgluWriteText(-37.0F, -459.25F, _lArray0_text_6, 255L);
            }

            /* Object: line_6, Type: line, OID: 60e31aef-631c-485f-96ab-7b88de6cb739 */
            {
              /* outlined object part */
              sglIndexLineWidthi(0L);
              sglBegin(SGL_LINES);
              sglVertex2f(-16.0F, -438.0F);
              sglVertex2f(-15.875F, -443.75F);
            }

            /* Object: line_7, Type: line, OID: 361f3f94-b926-4d2a-bb11-15758d861717 */
            {
              /* outlined object part */
              sglVertex2f(-11.375F, -437.875F);
              sglVertex2f(-11.375F, -444.125F);
              sglEnd();
            }

            /* Object: LAT_M, Type: text, OID: 3ebf92fb-a1bc-4f91-aea3-a1709ecb1252 */
            {
              sglIndexFonti(3L);
              sgluWriteText(-93.25F, -460.0F, aol_symbology_layer_G_LAT_M(pContext), 255L);
            }

            /* Object: LAT_S, Type: text, OID: f068671a-368c-4b32-981f-6bfaf08841c6 */
            {
              sgluWriteText(-49.25F, -460.0F, aol_symbology_layer_G_LAT_S(pContext), 255L);
            }
            sglPopMatrixAndTranslate();
          }

          /* Object: compass, Type: container, OID: 428e375a-e4cb-4204-9df8-2f83b748c22f */
          {
            SGLuint32 _lMask_stencil = SGL_NO_MASK;
            sglPushMatrixAndTranslate(0.0F, 43.0F);

            /* Object: stencil, Type: stencil, OID: c8d368f4-138f-4f62-9fe1-445ee17b3f82 */
            {
              sglDisable(SGL_TESSELLATION);
              _lMask_stencil = sglAllocateMaskID(SGL_TYPE_STENCIL);
              sglBegin((SGLuint8)_lMask_stencil);
              sglVertex2f(0.614986F, 0.614972F);
              sglVertex2f(-263.0F, 260.0F);
              sglVertex2f(-168.0F, 323.0F);
              sgluArcSegment(SGL_TRUE, 34.301423F);
              sglVertex2f(-40.0F, 362.0F);
              sgluArcSegment(SGL_TRUE, 26.162036F);
              sglVertex2f(160.0F, 325.0F);
              sglVertex2f(255.0F, 268.0F);
              sgluArcSegment(SGL_TRUE, 52.243648F);
              sglVertex2f(237.0F, 235.0F);
              sglEnd();
            }

            /* Object: circle, Type: circle, OID: b4ef7180-b0c3-48ac-b4a5-59d36638ab38 */
            {
              sglSetActiveMasks(_lMask_stencil);
              /* outlined object part */
              sglIndexColori(2L);
              sglIndexLineWidthi(1L);
              sgluArcSector2f(-1.5e-005F, -2.8e-005F, 336.072909F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_CIRCLE_LINE);
            }

            /* Object: rotate_group, Type: functionalRotate, OID: bb78b892-56ae-42b3-b13f-b468a52b2d3e */
            {
              sglPushMatrix();
              sglRotatef(aol_symbology_layer_G_tHdg(pContext));

              /* Object: compass_1, Type: container, OID: 732b66af-f5e9-4cd9-93a7-5d739f3332e6 */
              {

                /* Object: group_1, Type: container, OID: 8473d41b-679f-4169-992d-881fe0438816 */
                {
                  sglPushMatrixAndTranslate(0.0F, -1.0F);

                  /* Object: line_8, Type: line, OID: d5af1e15-fd36-4c88-abcb-4800a3dca861 */
                  {
                    /* outlined object part */
                    sglBegin(SGL_LINES);
                    sglVertex2f(0.0F, 351.75F);
                    sglVertex2f(0.499982F, 336.099976F);
                  }

                  /* Object: line_9, Type: line, OID: bd3f01a5-949d-4c3b-a59a-a172d1ed777b */
                  {
                    /* outlined object part */
                    sglVertex2f(-61.080746F, 346.406128F);
                    sglVertex2f(-57.870762F, 331.080688F);
                  }

                  /* Object: line_10, Type: line, OID: cf7f6eca-14f9-4581-a910-83927306681d */
                  {
                    /* outlined object part */
                    sglVertex2f(-120.305588F, 330.536865F);
                    sglVertex2f(-114.483131F, 316.001678F);
                  }

                  /* Object: line_11, Type: line, OID: 8902f649-a2d0-49a9-ace0-db78f02f02c8 */
                  {
                    /* outlined object part */
                    sglVertex2f(-175.875F, 304.62442F);
                    sglVertex2f(-167.616989F, 291.321106F);
                  }

                  /* Object: line_12, Type: line, OID: 411d4b65-775a-4322-829b-83f119ee1804 */
                  {
                    /* outlined object part */
                    sglVertex2f(-226.10054F, 269.456116F);
                    sglVertex2f(-215.657883F, 257.78891F);
                  }

                  /* Object: line_13, Type: line, OID: 95cd9f25-cc97-4402-b62e-b830990d9372 */
                  {
                    /* outlined object part */
                    sglVertex2f(-269.456116F, 226.100525F);
                    sglVertex2f(-257.146118F, 216.42392F);
                  }

                  /* Object: line_14, Type: line, OID: 0c22c88e-79e8-4db5-827d-b46e9ce6d29a */
                  {
                    /* outlined object part */
                    sglVertex2f(-304.62442F, 175.874985F);
                    sglVertex2f(-290.821106F, 168.483002F);
                  }

                  /* Object: line_15, Type: line, OID: 2f334391-2c06-4f59-9d7a-c4b347579307 */
                  {
                    /* outlined object part */
                    sglVertex2f(-330.536865F, 120.305573F);
                    sglVertex2f(-315.659637F, 115.422813F);
                  }

                  /* Object: line_16, Type: line, OID: 4f1c45ce-7a9b-43fb-ba71-61d44a16cfe3 */
                  {
                    /* outlined object part */
                    sglVertex2f(-346.406097F, 61.080738F);
                    sglVertex2f(-330.907013F, 58.85556F);
                  }

                  /* Object: line_17, Type: line, OID: 1115beaf-c1d6-4a21-a960-be112c90469d */
                  {
                    /* outlined object part */
                    sglVertex2f(-351.749969F, -3e-006F);
                    sglVertex2f(-336.099945F, 0.500012F);
                  }

                  /* Object: line_18, Type: line, OID: f025cd9b-42a0-4615-9ff7-a0abf5ec4a8a */
                  {
                    /* outlined object part */
                    sglVertex2f(-346.406097F, -61.080746F);
                    sglVertex2f(-331.080658F, -57.870728F);
                  }

                  /* Object: line_19, Type: line, OID: 77486da5-71d4-45c1-846a-ba310cc730be */
                  {
                    /* outlined object part */
                    sglVertex2f(-330.536865F, -120.30558F);
                    sglVertex2f(-316.001648F, -114.483093F);
                  }

                  /* Object: line_20, Type: line, OID: b48a1cff-8fef-4166-b69e-3826f2961a5d */
                  {
                    /* outlined object part */
                    sglVertex2f(-304.62442F, -175.874985F);
                    sglVertex2f(-291.321106F, -167.616943F);
                  }

                  /* Object: line_21, Type: line, OID: 0e933054-df4a-42f3-a5b6-2b156a091581 */
                  {
                    /* outlined object part */
                    sglVertex2f(-269.456116F, -226.100525F);
                    sglVertex2f(-257.78891F, -215.657837F);
                  }

                  /* Object: line_22, Type: line, OID: 03229cd5-f728-4e88-9bcc-b02ef89b26cb */
                  {
                    /* outlined object part */
                    sglVertex2f(-226.100525F, -269.456116F);
                    sglVertex2f(-216.42392F, -257.146088F);
                  }

                  /* Object: line_23, Type: line, OID: 04f9a873-b30e-4792-bca2-349020c53142 */
                  {
                    /* outlined object part */
                    sglVertex2f(-175.874985F, -304.62442F);
                    sglVertex2f(-168.483002F, -290.821075F);
                  }

                  /* Object: line_24, Type: line, OID: ca340134-93be-4dbd-a45a-38a586c45adb */
                  {
                    /* outlined object part */
                    sglVertex2f(-120.305573F, -330.536865F);
                    sglVertex2f(-115.422813F, -315.659607F);
                  }

                  /* Object: line_25, Type: line, OID: f5f48b8a-e36a-49f2-8bfe-ac220c5b16fb */
                  {
                    /* outlined object part */
                    sglVertex2f(-61.080738F, -346.406097F);
                    sglVertex2f(-58.855564F, -330.906982F);
                  }

                  /* Object: line_26, Type: line, OID: 33ac4926-b855-4b3b-b55d-297a727f0cd7 */
                  {
                    /* outlined object part */
                    sglVertex2f(3e-006F, -351.749969F);
                    sglVertex2f(-0.500021F, -336.099915F);
                  }

                  /* Object: line_27, Type: line, OID: e742247b-547a-4eef-862a-ca47c74016c8 */
                  {
                    /* outlined object part */
                    sglVertex2f(61.080746F, -346.406097F);
                    sglVertex2f(57.870712F, -331.080627F);
                  }

                  /* Object: line_28, Type: line, OID: ea4348f0-1ffc-4869-9aad-a4f0d331e2f0 */
                  {
                    /* outlined object part */
                    sglVertex2f(120.30558F, -330.536865F);
                    sglVertex2f(114.48307F, -316.001617F);
                  }

                  /* Object: line_29, Type: line, OID: fd0710db-6428-4247-bc20-fbdc5c4354c4 */
                  {
                    /* outlined object part */
                    sglVertex2f(175.874985F, -304.62442F);
                    sglVertex2f(167.616913F, -291.321075F);
                  }

                  /* Object: line_30, Type: line, OID: bbc09433-a296-4419-902a-1aec0cb2fafb */
                  {
                    /* outlined object part */
                    sglVertex2f(226.100525F, -269.456116F);
                    sglVertex2f(215.657806F, -257.788879F);
                  }

                  /* Object: line_31, Type: line, OID: eb1df089-bfaf-4815-b004-1e0bc59d3eb5 */
                  {
                    /* outlined object part */
                    sglVertex2f(269.456116F, -226.100525F);
                    sglVertex2f(257.146057F, -216.423904F);
                  }

                  /* Object: line_32, Type: line, OID: a2e6ec00-74c1-4788-828d-480ac0a8a374 */
                  {
                    /* outlined object part */
                    sglVertex2f(304.62442F, -175.874985F);
                    sglVertex2f(290.821045F, -168.483002F);
                  }

                  /* Object: line_33, Type: line, OID: 5617dd5a-9180-475c-a0ad-3d22e0d36dfd */
                  {
                    /* outlined object part */
                    sglVertex2f(330.536865F, -120.305573F);
                    sglVertex2f(315.659576F, -115.422821F);
                  }

                  /* Object: line_34, Type: line, OID: 3313853f-ad33-4cef-9c99-587264ece0a8 */
                  {
                    /* outlined object part */
                    sglVertex2f(346.406097F, -61.080738F);
                    sglVertex2f(330.906952F, -58.855579F);
                  }

                  /* Object: line_35, Type: line, OID: 286cbca2-1f70-442b-8ded-e070a5a7303d */
                  {
                    /* outlined object part */
                    sglVertex2f(351.749969F, 3e-006F);
                    sglVertex2f(336.099884F, -0.500042F);
                  }

                  /* Object: line_36, Type: line, OID: 3db1bbdc-15d9-4642-b5d7-1585e54d4992 */
                  {
                    /* outlined object part */
                    sglVertex2f(346.406097F, 61.080746F);
                    sglVertex2f(331.080597F, 57.870686F);
                  }

                  /* Object: line_37, Type: line, OID: 96bc3144-d5ce-45a7-9b6b-964f8f09b5d1 */
                  {
                    /* outlined object part */
                    sglVertex2f(330.536865F, 120.30558F);
                    sglVertex2f(316.001587F, 114.48304F);
                  }

                  /* Object: line_38, Type: line, OID: 2f2daaf3-b720-459e-93af-a1d77b8e1e69 */
                  {
                    /* outlined object part */
                    sglVertex2f(304.62442F, 175.874985F);
                    sglVertex2f(291.321045F, 167.616882F);
                  }

                  /* Object: line_39, Type: line, OID: 5f1d8a9d-2d3f-47f8-aa41-b3b339ba791f */
                  {
                    /* outlined object part */
                    sglVertex2f(269.456116F, 226.100525F);
                    sglVertex2f(257.788849F, 215.657776F);
                  }

                  /* Object: line_40, Type: line, OID: 6309da7f-5e89-48af-87f6-eb507ba2c767 */
                  {
                    /* outlined object part */
                    sglVertex2f(226.100525F, 269.456116F);
                    sglVertex2f(216.423874F, 257.146027F);
                  }

                  /* Object: line_41, Type: line, OID: 6d99e631-956e-4917-a502-27b3cb09412e */
                  {
                    /* outlined object part */
                    sglVertex2f(175.874985F, 304.62442F);
                    sglVertex2f(168.482971F, 290.821014F);
                  }

                  /* Object: line_42, Type: line, OID: 8620c64f-cd04-4492-9ef0-0e628c16516e */
                  {
                    /* outlined object part */
                    sglVertex2f(120.305573F, 330.536865F);
                    sglVertex2f(115.422798F, 315.659546F);
                  }

                  /* Object: line_43, Type: line, OID: dd6f0e58-4974-400d-87d8-b6c63d264984 */
                  {
                    /* outlined object part */
                    sglVertex2f(61.080738F, 346.406097F);
                    sglVertex2f(58.85556F, 330.906921F);
                  }

                  /* Object: line_44, Type: line, OID: 884282d8-81c4-4e91-bc59-67d403ab78fa */
                  {
                    /* outlined object part */
                    sglVertex2f(-29.846157F, 342.577332F);
                    sglVertex2f(-29.283985F, 334.733459F);
                  }

                  /* Object: line_45, Type: line, OID: 8cf443e8-8e08-4b36-affc-d8639734fffa */
                  {
                    /* outlined object part */
                    sglVertex2f(-88.880653F, 332.190094F);
                    sglVertex2f(-86.964951F, 324.562988F);
                  }

                  /* Object: line_46, Type: line, OID: 03c644fd-2b5a-4cf3-ac2c-d01534d7f357 */
                  {
                    /* outlined object part */
                    sglVertex2f(-145.214554F, 311.709412F);
                    sglVertex2f(-142.003525F, 304.530853F);
                  }

                  /* Object: line_47, Type: line, OID: 0f92d418-e926-4306-9e06-38431d2893d6 */
                  {
                    /* outlined object part */
                    sglVertex2f(-197.136185F, 281.757599F);
                    sglVertex2f(-192.727402F, 275.245697F);
                  }

                  /* Object: line_48, Type: line, OID: 9c3ae646-57c4-4b28-9684-34ecd807da68 */
                  {
                    /* outlined object part */
                    sglVertex2f(-243.067932F, 243.244736F);
                    sglVertex2f(-237.595352F, 237.597336F);
                  }

                  /* Object: line_49, Type: line, OID: d8763be2-95cd-4750-ab71-8700d2e68102 */
                  {
                    /* outlined object part */
                    sglVertex2f(-281.614197F, 197.341003F);
                    sglVertex2f(-275.24408F, 192.729706F);
                  }

                  /* Object: line_50, Type: line, OID: 70cccd5b-0969-4a12-b3fc-8fe31809f96c */
                  {
                    /* outlined object part */
                    sglVertex2f(-311.60376F, 145.441162F);
                    sglVertex2f(-304.529663F, 142.006073F);
                  }

                  /* Object: line_51, Type: line, OID: d96a18c3-431e-45b5-990c-9a56a201a637 */
                  {
                    /* outlined object part */
                    sglVertex2f(-332.125397F, 89.122162F);
                    sglVertex2f(-324.562256F, 86.967659F);
                  }

                  /* Object: line_52, Type: line, OID: 2ab64e3d-531f-4b02-b47b-ea70f132fc6f */
                  {
                    /* outlined object part */
                    sglVertex2f(-342.555573F, 30.095226F);
                    sglVertex2f(-334.733215F, 29.286781F);
                  }

                  /* Object: line_53, Type: line, OID: 5e971821-dc7c-458d-9a3e-2f7faf24b944 */
                  {
                    /* outlined object part */
                    sglVertex2f(-342.577362F, -29.846138F);
                    sglVertex2f(-334.733459F, -29.283964F);
                  }

                  /* Object: line_54, Type: line, OID: 8bf58f30-8115-4a80-8747-be72848200a2 */
                  {
                    /* outlined object part */
                    sglVertex2f(-332.190125F, -88.880646F);
                    sglVertex2f(-324.562988F, -86.964928F);
                  }

                  /* Object: line_55, Type: line, OID: 63d6807a-9791-4ed0-bb6d-ac743fe03472 */
                  {
                    /* outlined object part */
                    sglVertex2f(-311.709442F, -145.214554F);
                    sglVertex2f(-304.530853F, -142.00351F);
                  }

                  /* Object: line_56, Type: line, OID: a419af02-8c0b-438d-9177-2b411925a87b */
                  {
                    /* outlined object part */
                    sglVertex2f(-281.757629F, -197.1362F);
                    sglVertex2f(-275.245697F, -192.727386F);
                  }

                  /* Object: line_57, Type: line, OID: 80a4f77d-461a-4fab-990b-1ff96a6a58b8 */
                  {
                    /* outlined object part */
                    sglVertex2f(-243.244751F, -243.067963F);
                    sglVertex2f(-237.597336F, -237.595337F);
                  }

                  /* Object: line_58, Type: line, OID: 5550414c-c45e-4943-8835-b68945f8b950 */
                  {
                    /* outlined object part */
                    sglVertex2f(-197.341003F, -281.614227F);
                    sglVertex2f(-192.729706F, -275.24408F);
                  }

                  /* Object: line_59, Type: line, OID: 91c64d62-9f0f-4675-83f2-9323fbeca317 */
                  {
                    /* outlined object part */
                    sglVertex2f(-145.441147F, -311.60379F);
                    sglVertex2f(-142.006073F, -304.529663F);
                  }

                  /* Object: line_60, Type: line, OID: f83d21df-5f94-4806-9da3-8b8eba0e021a */
                  {
                    /* outlined object part */
                    sglVertex2f(-89.122139F, -332.125427F);
                    sglVertex2f(-86.967659F, -324.562256F);
                  }

                  /* Object: line_61, Type: line, OID: d1aa128b-ed44-4ec8-8007-8db3e7837613 */
                  {
                    /* outlined object part */
                    sglVertex2f(-30.095198F, -342.555603F);
                    sglVertex2f(-29.286781F, -334.733215F);
                  }

                  /* Object: line_62, Type: line, OID: ade6bfb3-b898-41c1-8051-9b03f4c787f5 */
                  {
                    /* outlined object part */
                    sglVertex2f(29.846172F, -342.577393F);
                    sglVertex2f(29.283964F, -334.733459F);
                  }

                  /* Object: line_63, Type: line, OID: 1139f9ae-df86-43ee-80be-fcb02d958d1d */
                  {
                    /* outlined object part */
                    sglVertex2f(88.880684F, -332.190125F);
                    sglVertex2f(86.964928F, -324.562988F);
                  }

                  /* Object: line_64, Type: line, OID: 2299819d-1a01-4a6d-9e54-d568e111bf86 */
                  {
                    /* outlined object part */
                    sglVertex2f(145.2146F, -311.709442F);
                    sglVertex2f(142.00351F, -304.530853F);
                  }

                  /* Object: line_65, Type: line, OID: 88effb13-c19f-47f7-bae7-d2cfb5c9ac8f */
                  {
                    /* outlined object part */
                    sglVertex2f(197.136246F, -281.757629F);
                    sglVertex2f(192.727386F, -275.245697F);
                  }

                  /* Object: line_66, Type: line, OID: 0f178228-bdaf-4003-9174-177e60733630 */
                  {
                    /* outlined object part */
                    sglVertex2f(243.068008F, -243.244751F);
                    sglVertex2f(237.595337F, -237.597336F);
                  }

                  /* Object: line_67, Type: line, OID: ae5a0ae8-5bfa-4ebf-898d-fe6b9235c020 */
                  {
                    /* outlined object part */
                    sglVertex2f(281.614258F, -197.341003F);
                    sglVertex2f(275.24408F, -192.729706F);
                  }

                  /* Object: line_68, Type: line, OID: 6200d93c-e735-497c-adf5-3bbe890323b1 */
                  {
                    /* outlined object part */
                    sglVertex2f(311.603821F, -145.441147F);
                    sglVertex2f(304.529663F, -142.006073F);
                  }

                  /* Object: line_69, Type: line, OID: 9bb061e2-f582-4eff-ae20-01806f4bc8cc */
                  {
                    /* outlined object part */
                    sglVertex2f(332.125458F, -89.122131F);
                    sglVertex2f(324.562256F, -86.967659F);
                  }

                  /* Object: line_70, Type: line, OID: 6dcb20de-661a-4024-abcd-1c9349e5a302 */
                  {
                    /* outlined object part */
                    sglVertex2f(342.555634F, -30.095186F);
                    sglVertex2f(334.733215F, -29.286781F);
                  }

                  /* Object: line_71, Type: line, OID: 143706b3-0680-4da4-9ad0-a2d91e289b3a */
                  {
                    /* outlined object part */
                    sglVertex2f(342.577423F, 29.846189F);
                    sglVertex2f(334.733459F, 29.283964F);
                  }

                  /* Object: line_72, Type: line, OID: 361fcd56-286b-43b2-a8fa-2a9a674b5ea4 */
                  {
                    /* outlined object part */
                    sglVertex2f(332.190155F, 88.880707F);
                    sglVertex2f(324.562988F, 86.964928F);
                  }

                  /* Object: line_73, Type: line, OID: b531e349-4d99-4169-8e69-5aacf776d069 */
                  {
                    /* outlined object part */
                    sglVertex2f(311.709473F, 145.21463F);
                    sglVertex2f(304.530853F, 142.00351F);
                  }

                  /* Object: line_74, Type: line, OID: 7b6f97de-926a-403a-afd7-3421b1b110bc */
                  {
                    /* outlined object part */
                    sglVertex2f(281.75766F, 197.136276F);
                    sglVertex2f(275.245697F, 192.727386F);
                  }

                  /* Object: line_75, Type: line, OID: 370e3b74-1a43-4cf0-b30c-8037a3aa8435 */
                  {
                    /* outlined object part */
                    sglVertex2f(243.244766F, 243.068039F);
                    sglVertex2f(237.597336F, 237.595337F);
                  }

                  /* Object: line_76, Type: line, OID: 72e8301a-0cfe-4a4d-989a-6c5c9721e12c */
                  {
                    /* outlined object part */
                    sglVertex2f(197.341003F, 281.614288F);
                    sglVertex2f(192.729706F, 275.24408F);
                  }

                  /* Object: line_77, Type: line, OID: 0e25b5bc-f630-4839-98bd-9f0d4dab59a7 */
                  {
                    /* outlined object part */
                    sglVertex2f(145.441147F, 311.603851F);
                    sglVertex2f(142.006073F, 304.529663F);
                  }

                  /* Object: line_78, Type: line, OID: 947b77b0-6e85-4dea-a49f-5b47c847f3d6 */
                  {
                    /* outlined object part */
                    sglVertex2f(89.122131F, 332.125488F);
                    sglVertex2f(86.967659F, 324.562256F);
                  }

                  /* Object: line_79, Type: line, OID: df0636c7-f64d-4027-bb8b-a9ea40f46697 */
                  {
                    /* outlined object part */
                    sglVertex2f(30.095181F, 342.555664F);
                    sglVertex2f(29.286781F, 334.733215F);
                    sglEnd();
                  }
                  sglPopMatrixAndTranslate();
                }
              }

              /* Object: number, Type: container, OID: 4e6250e8-9e1b-4ec2-a0f7-9300ba26860c */
              {

                /* Object: 0, Type: text, OID: 83c857a9-be62-4740-a735-f8e472f4098f */
                {
                  static SGLuint8 _lArray0_0[255UL] = {48U};
                  sglIndexFonti(5L);
                  sgluWriteText(-5.915014F, 317.980011F, _lArray0_0, 255L);
                }

                /* Object: group_2, Type: container, OID: 9c9addff-3883-4fa0-a04f-68909a607a9d */
                {
                  sglPushMatrix();
                  sglRotatef(70.0F);

                  /* Object: 29, Type: text, OID: 4ff2a11e-8146-47ab-b112-d2353c0b5343 */
                  {
                    static SGLuint8 _lArray0_29[255UL] = {50U,57U};
                    sgluWriteText(-14.680025F, 315.824982F, _lArray0_29, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_3, Type: container, OID: 426e0ab4-9efb-4cf4-9246-55866e38f0a5 */
                {
                  sglPushMatrix();
                  sglRotatef(10.0F);

                  /* Object: 35, Type: text, OID: 9ac5f2df-4b2d-455a-9112-332c798fef50 */
                  {
                    static SGLuint8 _lArray0_35[255UL] = {51U,53U};
                    sgluWriteText(-14.680025F, 315.824982F, _lArray0_35, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_4, Type: container, OID: a8694749-819e-41f3-a1f2-180318f456c3 */
                {
                  sglPushMatrix();
                  sglRotatef(20.0F);

                  /* Object: 34, Type: text, OID: 609ad45a-d503-4369-a3fa-6f7b93f23898 */
                  {
                    static SGLuint8 _lArray0_34[255UL] = {51U,52U};
                    sgluWriteText(-14.680025F, 315.824982F, _lArray0_34, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_5, Type: container, OID: 59757fcc-a6e8-4744-9044-f196fe1d6ca8 */
                {
                  sglPushMatrix();
                  sglRotatef(310.0F);

                  /* Object: 5, Type: text, OID: e1b1e112-e398-4d1a-ab9c-caf1d3108f77 */
                  {
                    static SGLuint8 _lArray0_5[255UL] = {53U};
                    sgluWriteText(-9.224998F, 312.97998F, _lArray0_5, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_6, Type: container, OID: 950e6400-ab47-4ac1-b4fd-e734678d1143 */
                {
                  sglPushMatrix();
                  sglRotatef(320.0F);

                  /* Object: 4, Type: text, OID: d2db86d8-c7c2-47fd-b296-825a36e0af65 */
                  {
                    static SGLuint8 _lArray0_4[255UL] = {52U};
                    sgluWriteText(-9.224998F, 312.97998F, _lArray0_4, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_7, Type: container, OID: 0689debc-e644-4d5b-b1da-47356f70dd8d */
                {
                  sglPushMatrix();
                  sglRotatef(350.0F);

                  /* Object: 1, Type: text, OID: 9c6b5fdb-4ecb-456e-91d9-7b1f983e388e */
                  {
                    static SGLuint8 _lArray0_1[255UL] = {49U};
                    sgluWriteText(-9.224998F, 312.97998F, _lArray0_1, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_8, Type: container, OID: 56820514-d87c-4d2d-8cfd-90f9eca0d079 */
                {
                  sglPushMatrix();
                  sglRotatef(50.0F);

                  /* Object: 31, Type: text, OID: a2e2e813-1af6-4f5b-8f83-b01146250ee4 */
                  {
                    static SGLuint8 _lArray0_31[255UL] = {51U,49U};
                    sgluWriteText(-14.680025F, 315.824982F, _lArray0_31, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_9, Type: container, OID: 795f4863-8258-4eb0-8d29-fad9fc0c83d6 */
                {
                  sglPushMatrix();
                  sglRotatef(40.0F);

                  /* Object: 32, Type: text, OID: 3a9f4b9a-6dee-4fba-ad5d-129013514635 */
                  {
                    static SGLuint8 _lArray0_32[255UL] = {51U,50U};
                    sgluWriteText(-14.680025F, 315.824982F, _lArray0_32, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_10, Type: container, OID: ca2de271-54f1-46bd-ac3a-5e737a7c7ee8 */
                {
                  sglPushMatrix();
                  sglRotatef(100.0F);

                  /* Object: 26, Type: text, OID: 327c5e9d-5d2a-43e2-a9ce-35637459454c */
                  {
                    static SGLuint8 _lArray0_26[255UL] = {50U,54U};
                    sgluWriteText(-13.375028F, 315.365051F, _lArray0_26, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_11, Type: container, OID: 086a4f7f-8174-4dbe-9995-b95b90d84cd8 */
                {
                  sglPushMatrix();
                  sglRotatef(90.0F);

                  /* Object: 27, Type: text, OID: 3f30b4cb-449a-459a-b5e2-36a9be9a593e */
                  {
                    static SGLuint8 _lArray0_27[255UL] = {50U,55U};
                    sgluWriteText(-13.375029F, 315.365051F, _lArray0_27, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_12, Type: container, OID: 410a32f8-c7be-418f-8432-b01fd76299f7 */
                {
                  sglPushMatrix();
                  sglRotatef(80.0F);

                  /* Object: 28, Type: text, OID: 1bcfac32-7cef-41a2-9a59-580a72108889 */
                  {
                    static SGLuint8 _lArray0_28[255UL] = {50U,56U};
                    sgluWriteText(-14.680025F, 315.824982F, _lArray0_28, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_13, Type: container, OID: 8c20228f-0159-4206-a852-6b3ea923f7ef */
                {
                  sglPushMatrix();
                  sglRotatef(30.0F);

                  /* Object: 33, Type: text, OID: 3c0822c6-28ba-4abf-88af-344b69740ce7 */
                  {
                    static SGLuint8 _lArray0_33[255UL] = {51U,51U};
                    sgluWriteText(-14.680025F, 315.824982F, _lArray0_33, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_14, Type: container, OID: 791004f4-e7c3-4931-8925-451b2ec9d354 */
                {
                  sglPushMatrix();
                  sglRotatef(60.0F);

                  /* Object: 30, Type: text, OID: 36503093-f16f-4860-87f1-8b62423d062d */
                  {
                    static SGLuint8 _lArray0_30[255UL] = {51U,48U};
                    sgluWriteText(-15.065035F, 313.75F, _lArray0_30, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_15, Type: container, OID: 05dab54c-4e67-49c0-a42f-3af2be772c51 */
                {
                  sglPushMatrix();
                  sglRotatef(120.0F);

                  /* Object: 24, Type: text, OID: 0938fdd4-b257-46d4-a785-659d689d6e7f */
                  {
                    static SGLuint8 _lArray0_24[255UL] = {50U,52U};
                    sgluWriteText(-14.065018F, 315.440002F, _lArray0_24, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_16, Type: container, OID: e9722680-2178-434a-874f-f74b5e1a789e */
                {
                  sglPushMatrix();
                  sglRotatef(150.0F);

                  /* Object: 21, Type: text, OID: 9952cf9f-5fc2-4709-9753-180add7f102e */
                  {
                    static SGLuint8 _lArray0_21[255UL] = {50U,49U};
                    sgluWriteText(-12.605005F, 317.980072F, _lArray0_21, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_17, Type: container, OID: b7bb8691-16a8-425f-b043-c4c8799c5bac */
                {
                  sglPushMatrix();
                  sglRotatef(180.0F);

                  /* Object: 18, Type: text, OID: e084409e-fec2-4f5c-8559-de75448a50c8 */
                  {
                    static SGLuint8 _lArray0_18[255UL] = {49U,56U};
                    sgluWriteText(-11.454987F, 318.980042F, _lArray0_18, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_18, Type: container, OID: b88ccc04-66b7-41f8-8d62-3e9984837a6e */
                {
                  sglPushMatrix();
                  sglRotatef(210.0F);

                  /* Object: 15, Type: text, OID: 37b2d211-339c-451f-bbb9-3b188eec64e5 */
                  {
                    static SGLuint8 _lArray0_15[255UL] = {49U,53U};
                    sgluWriteText(-13.064976F, 317.210052F, _lArray0_15, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_19, Type: container, OID: c11988a8-584b-4fa2-a071-bbfcdfa44cf2 */
                {
                  sglPushMatrix();
                  sglRotatef(250.0F);

                  /* Object: 11, Type: text, OID: 741f02b1-4f40-4dd4-8bf6-2154785553bb */
                  {
                    static SGLuint8 _lArray0_11[255UL] = {49U,49U};
                    sgluWriteText(-12.29497F, 318.750061F, _lArray0_11, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_20, Type: container, OID: 500a5560-ac9a-4696-8b54-b87a2eac0460 */
                {
                  sglPushMatrix();
                  sglRotatef(240.0F);

                  /* Object: 12, Type: text, OID: 2fbc2b82-3c51-42d9-8471-2f61897e10a0 */
                  {
                    static SGLuint8 _lArray0_12[255UL] = {49U,50U};
                    sgluWriteText(-12.29497F, 318.750061F, _lArray0_12, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_21, Type: container, OID: 00910a35-25cb-4c6c-ab8f-66d18caf5b56 */
                {
                  sglPushMatrix();
                  sglRotatef(270.0F);

                  /* Object: E_1, Type: text, OID: f21e5959-43d0-41f2-976b-d3837e89f5c1 */
                  {
                    static SGLuint8 _lArray0_E_1[255UL] = {57U};
                    sgluWriteText(-6.914973F, 318.980011F, _lArray0_E_1, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_22, Type: container, OID: bd20e12c-e770-4371-8479-066b929692b6 */
                {
                  sglPushMatrix();
                  sglRotatef(300.0F);

                  /* Object: 6, Type: text, OID: 18b77e31-cd82-4b22-81fa-ce0fa89c99a8 */
                  {
                    static SGLuint8 _lArray0_6[255UL] = {54U};
                    sgluWriteText(-9.684983F, 317.52002F, _lArray0_6, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_23, Type: container, OID: e556949c-8bfa-48b0-97fe-63a95abda9d0 */
                {
                  sglPushMatrix();
                  sglRotatef(340.0F);

                  /* Object: 2, Type: text, OID: 06bf9788-0002-4ce1-bc20-8a48042d5ffd */
                  {
                    static SGLuint8 _lArray0_2[255UL] = {50U};
                    sgluWriteText(-9.224998F, 312.97998F, _lArray0_2, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_24, Type: container, OID: c50f0a81-c172-4fbe-ba43-a81a5ebb57b2 */
                {
                  sglPushMatrix();
                  sglRotatef(330.0F);

                  /* Object: 3, Type: text, OID: b6002df3-c829-4333-bf28-f0168b4b2201 */
                  {
                    static SGLuint8 _lArray0_3[255UL] = {51U};
                    sgluWriteText(-9.224998F, 312.97998F, _lArray0_3, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_25, Type: container, OID: 5dfb32d3-9cc6-4a23-aabb-5b5e3576d70a */
                {
                  sglPushMatrix();
                  sglRotatef(110.0F);

                  /* Object: 25, Type: text, OID: 4978d21b-88d7-4a1d-ad69-ac2424e039d5 */
                  {
                    static SGLuint8 _lArray0_25[255UL] = {50U,53U};
                    sgluWriteText(-14.680025F, 315.824982F, _lArray0_25, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_26, Type: container, OID: b7d34fb5-2f0f-4c7c-95fb-51837ad020a9 */
                {
                  sglPushMatrix();
                  sglRotatef(290.0F);

                  /* Object: 7, Type: text, OID: 5d1f80cc-df7f-4550-935d-84a27f4cb1b1 */
                  {
                    static SGLuint8 _lArray0_7[255UL] = {55U};
                    sgluWriteText(-9.224998F, 312.97998F, _lArray0_7, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_27, Type: container, OID: c19355a3-9f62-4b58-84e2-8c6e3d34df6a */
                {
                  sglPushMatrix();
                  sglRotatef(280.0F);

                  /* Object: 8, Type: text, OID: ffd7968e-3397-4e50-a076-76c519dd1974 */
                  {
                    static SGLuint8 _lArray0_8[255UL] = {56U};
                    sgluWriteText(-9.224998F, 312.97998F, _lArray0_8, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_28, Type: container, OID: fddbcdd9-ba14-44a0-8ca7-d64c1d42a129 */
                {
                  sglPushMatrix();
                  sglRotatef(140.0F);

                  /* Object: 22, Type: text, OID: b32f38ce-3b8c-4542-add6-ce6548f1b28f */
                  {
                    static SGLuint8 _lArray0_22[255UL] = {50U,50U};
                    sgluWriteText(-12.605005F, 317.980072F, _lArray0_22, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_29, Type: container, OID: 1f9d6162-97d8-461f-8a47-a9699493bf88 */
                {
                  sglPushMatrix();
                  sglRotatef(130.0F);

                  /* Object: 23, Type: text, OID: f19f68ad-d65b-4243-ad50-ebe83240a2d8 */
                  {
                    static SGLuint8 _lArray0_23[255UL] = {50U,51U};
                    sgluWriteText(-12.605005F, 317.980072F, _lArray0_23, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_30, Type: container, OID: 60283f42-bd63-4c43-a524-9a7fc55d4a5b */
                {
                  sglPushMatrix();
                  sglRotatef(160.0F);

                  /* Object: 20, Type: text, OID: 0910a27e-17e8-4d3c-bc4f-47abf9a9a1cc */
                  {
                    static SGLuint8 _lArray0_20[255UL] = {50U,48U};
                    sgluWriteText(-12.605005F, 317.980072F, _lArray0_20, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_31, Type: container, OID: 87df3b28-688f-4281-ad53-0e3cbc74f25d */
                {
                  sglPushMatrix();
                  sglRotatef(170.0F);

                  /* Object: 19, Type: text, OID: 5eb8dbca-9500-47f8-9845-9fd5fd97aa41 */
                  {
                    static SGLuint8 _lArray0_19[255UL] = {49U,57U};
                    sgluWriteText(-12.605005F, 317.980072F, _lArray0_19, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_32, Type: container, OID: fb98c174-e85f-489e-bc2b-aa0d7496420b */
                {
                  sglPushMatrix();
                  sglRotatef(200.0F);

                  /* Object: 16, Type: text, OID: 1248e6ac-18cd-4868-80ec-3a48b099b087 */
                  {
                    static SGLuint8 _lArray0_16[255UL] = {49U,54U};
                    sgluWriteText(-13.064976F, 317.210052F, _lArray0_16, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_33, Type: container, OID: dae68aff-4d96-41fa-8ed7-19bcfa669c47 */
                {
                  sglPushMatrix();
                  sglRotatef(190.0F);

                  /* Object: 17, Type: text, OID: bb88be25-d6e0-4a7a-a884-f1174bc25678 */
                  {
                    static SGLuint8 _lArray0_17[255UL] = {49U,55U};
                    sgluWriteText(-13.064976F, 317.210052F, _lArray0_17, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_34, Type: container, OID: bd0ea992-2bc6-457c-ac3f-4a435501c115 */
                {
                  sglPushMatrix();
                  sglRotatef(230.0F);

                  /* Object: 13, Type: text, OID: c3bb1e36-0a0b-4759-b610-575b9b3c5449 */
                  {
                    static SGLuint8 _lArray0_13[255UL] = {49U,51U};
                    sgluWriteText(-13.064976F, 317.210052F, _lArray0_13, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_35, Type: container, OID: 8d921ba4-17cb-44be-8579-d5eb5e49b3e4 */
                {
                  sglPushMatrix();
                  sglRotatef(220.0F);

                  /* Object: 14, Type: text, OID: 758831d5-606a-40ab-86fb-a89b24380aa4 */
                  {
                    static SGLuint8 _lArray0_14[255UL] = {49U,52U};
                    sgluWriteText(-13.064976F, 317.210052F, _lArray0_14, 255L);
                  }
                  sglPopMatrix();
                }

                /* Object: group_36, Type: container, OID: c640586a-08b3-4754-9c0e-2e36f58bca36 */
                {
                  sglPushMatrix();
                  sglRotatef(260.0F);

                  /* Object: 10, Type: text, OID: a4e43009-1c17-40c5-a237-8287535bd549 */
                  {
                    static SGLuint8 _lArray0_10[255UL] = {49U,48U};
                    sgluWriteText(-12.29497F, 318.750061F, _lArray0_10, 255L);
                  }
                  sglPopMatrix();
                }
              }
              sglPopMatrix();
            }
            sglFreeMaskID(_lMask_stencil);
            sglPopMatrixAndTranslate();
          }
        }
      }
      sglPopMatrixAndTranslate();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2025-10-10T11:03:39
 *********************************************************/

