/*********************************************************
 **
 ** File  aol_texture_table.c
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3a (build i2)
 **
 ** Date of generation: 2025-10-10T11:03:23
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.3\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir E:\yxiang\gpuzx_scade\NDto2C\ND\specification_Code E:\yxiang\gpuzx_scade\NDto2C\ND\texture_table.stt
 *********************************************************/

#include "sgl.h"
#include "aol_texture_table.h"

/* Textures definition */
void aol_texture_table(void)
{

}

/*********************************************************
 ** End of file
 ** End of generation: 2025-10-10T11:03:23
 *********************************************************/

