/*********************************************************
 **
 ** File  aol_line_stipple_table.c
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.3a (build i2)
 **
 ** Date of generation: 2025-10-10T11:03:22
 ** Command line: C:\Program Files (x86)\Esterel Technologies\SCADE R17.3\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir E:\yxiang\gpuzx_scade\NDto2C\ND\specification_Code E:\yxiang\gpuzx_scade\NDto2C\ND\line_stipple_table.sst
 *********************************************************/

#include "aol_line_stipple_table.h"

/* Line stipple table definition */
const sgl_linestipple aol_line_stipple_table[5UL] = 
{
{ {   0,   0,   0,   0,   0,   0}, {   0,   0,   0,   0,   0,   0},   1,   0}, /*     0  solid  pattern :  */
{ {  12,  12,   0,   0,   0,   0}, {   1,   0,   0,   0,   0,   0},   0,   2}, /*     1  dashed pattern :  */
{ {   8,   8,   0,   0,   0,   0}, {   1,   0,   0,   0,   0,   0},   0,   2}, /*     2  dashed pattern :  */
{ {   1,   6,   0,   0,   0,   0}, {   1,   0,   0,   0,   0,   0},   0,   2}, /*     3  dashed pattern :  */
{ {   1,   8,   8,   8,   0,   0}, {   1,   0,   1,   0,   0,   0},   0,   4}  /*     4  dashed pattern :  */
};

SGLint32 aol_line_stipple_table_size = 5UL;

/*********************************************************
 ** End of file
 ** End of generation: 2025-10-10T11:03:22
 *********************************************************/

